name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          command_timeout: 40m 
          script: |
            # 1. Entrar a la carpeta y limpiar cambios locales si los hubiera
            cd ~/Zafiro_Frontend || exit
            
            # 2. Actualizar el código
            git pull origin main
            
            # 3. Instalar dependencias solo si es necesario
            npm install
            
            # 4. Construir el proyecto (Aquí es donde suele dar el timeout o falta de RAM)
            npm run build
            
            # 5. Reiniciar con PM2 (Si no existe el proceso, lo crea)
            pm2 restart all || pm2 start npm --name "zafiro-front" -- start